### ISSUE TITLE
UI elements

### ISSUE THREAD

**Issue by sephirob** [brycethorup/cash-class-tracker#15]
Window borders, backgrounds, space separation elements, Treehouse logo, Walton logo, etc

**Comment by sephirob** [comment]
Is Avenir a possible font? Primarily this would be in Black style and Medium style.

**Comment by brycethorup** [comment]
If you have a license that allows for embedding it in an application, it should be fine. When you find out, I'll need to get a copy to add it to the app.

**Comment by sephirob** [comment]
Actually, you've been using the one I had on the mockup, right? I think that one is great if we can go with it, was there some issue or am I remembering things wrongly? Too much going on haha...

**Comment by sephirob** [comment]
Marlboro it is. Thats what everything will be done with for this project, lynne approved.
