### ISSUE TITLE
Cash class (story problems) text for all questions

### ISSUE THREAD

**Issue by sephirob** [brycethorup/cash-class-tracker#23]
This also entails having the values for each fruit/veg that will be asked about. All values will be by the pound (tomatos are 19c per pound, mushrooms are 49c per pound), but it would be nice if there were some difficult questions that ask what coins would you use to pay for two pounds. 

• It may well be that we need a "difficulty" button that can live in the lower left of the screen in place of the square there. I'll consult lynne and see if she wants that as a feature, because then the questions could ask for more complex mental math operations and use higher value bills and such. 

• Maybe we also need a button that lives in the upper right corner in place of the square that will drop a random coin into play, just in case the user doesn't have enough?

• Maybe we also need a ? button that will display what the buttons are when touched, just as a quick overlay with some text indicators that goes away if anywhere on the screen is tapped. 

A text file with all the values and the question forms will provide this info

**Comment by brycethorup** [comment]
@sephirob I agree with the tutorial screen for sure. We can certainly mix it up with how the problems are worded. I don't think they need to each be unique, just different types (how much for x pounds of something at some value per pound? or x pounds of an item costs this much, which coins do you use?)

**Comment by brycethorup** [comment]
@sephirob also, were we going to have a set number of questions when the activity starts and then kick them back to the selection screen, or are we wanting continuous questions? I just noticed the "Question #4"  header on the question card in the activity layout file which, to me, implies the former.

**Comment by sephirob** [comment]
I'll add a ? button to the set I'm making, and that would be awesome with just a couple of different wordings. Lynne originally has it asking 5 specific different questions, but I think our method will be even better, and we'll just put a difficulty star rating over each question so you know how hard it is and thusly if its too tough you can then tap the difficulty button and scale it down. Probably 1-3 stars and really all they need to do is just ask for more operations mentally to figure out what coins you need to move across. 

New version of the Cash Class layout will be forth coming.

**Comment by sephirob** [comment]
Final version, which is now the Solve It layout.ai, is in the box with all graphics and text. Instead of a question # there are 1-3 stars to show difficulty, and the only button besides back on the layout is the difficulty selector button. There is one more thing coming as part of this and that is the difficulty selector window itself, which much like the congrats window, will be a thing unto itself in case we need it on another screen. Other than the difficulty selection however, this is now hopefully done.
