### ISSUE TITLE
List of amounts per pound for each item.

### ISSUE THREAD

**Issue by brycethorup** [brycethorup/cash-class-tracker#25]

**Comment by sephirob** [comment]
The list was changed to be cost per single item, and the per pound idea was tossed. 

I emailed this list, but I figure it doesn't hurt to have it elsewhere. 

Costs are as follows: 

tomato            10¢
red (or white) onion            3¢
bunch of radishes        12¢   
mushroom            1¢
potatoes            3¢
carrot                7¢
stalk of celery        13¢   
green (or yellow) pepper            3¢
cucumber            4¢
zucchini                6¢
apple                5¢
lemon                10¢
lime                29¢
orange            25¢
eggplant            20¢
head of lettuce        12¢
