### ISSUE TITLE
Create a box for combining money back into larger values

### ISSUE THREAD

**Issue by brycethorup** [brycethorup/cash-class-tracker#9]

**Comment by sephirob** [comment]
Could we perhaps have, instead, a button to click that drops a new coin of random value onto the screen, rather than needing the user to put money into something to get a bigger something? I'm not sure which way would be neater.

**Comment by brycethorup** [comment]
@sephirob That would be simpler. I'm trying to remember why we wanted to have this in the first place.

**Comment by sephirob** [comment]
Cant remember myself, seems better to just have a +coin button, which I have all ready to do. I'll make a file with just the buttons, back, +coin, difficulty, etc
